PGHOST="127.0.0.1"
PGPORT="5432"
PGUSER="backup_user"

BACKUP_DIR="/backups"
TMP_DIR="/var/tmp/postgresql-backup"

LOG_FILE="/var/log/postgresql-backup/backup.log"
RUN_DIR="/var/lib/backup/run"

SPACE_SAFETY_FACTOR=0.05

BACKUP_RETENTION_DAYS=14
